### ISSUE TITLE
Is this plugin is ready to use? How to Use this for iOS

### ISSUE THREAD

**Issue by izeryab** [PeiJueChen/capacitor-aigens-change-app-icon#1]
Is this plugin is complete and working i am also working on change app icon functionality for android and didn't find any plugin for android except this one

**Comment by PeiJueChen** [comment]
YES, it works  for me.

**Comment by izeryab** [comment]
@PeiJueChen do you have any capacitor test app in which you have used this plugin it will help to understand how to use this and that would be great

**Comment by PeiJueChen** [comment]
Sorry, I'm too busy at this time, I'll have to check later, but you can refer to the native code ? 
ios native: https://github.com/PeiJueChen/changeAppIcon-ios
android native: https://github.com/PeiJueChen/changeAppIcon-android
Note: for participation only.

**Comment by izeryab** [comment]
@PeiJueChen Thank you it will help
